### PR TITLE
Some improvements on "Nats to dims" branch

### PR DESCRIPTION
**Pull request by vilunov**
- merged master branch
- added tests
- replaced some type-level list operations with their implementations in `singletons`
- fixed `scalar` bounds
- added new `batchMatMul` op wrapper

### CODE REVIEW

**Comment by vilunov** [comment]
Btw, I'm thinking about adopting some kind of autoformatter, I'm not sure, however, which ones should I check out in Haskell ecosystem

**Comment by helq** [comment]
Hi Vilunov,

I'm checking the code. Everything seems to be fine. I'll finish tomorrow and merge your work.

Thanks

**Comment by vilunov** [comment]
Before you merge, perhaps you could elaborate on how you wanted the refactor to proceed? I'm not sure how changing Nats to Dims would help with dependently typed code, but my attempt on batch processing with runtime-defined dimension is not very eloquent and would hardly be useful in real life situations.

**Comment by helq** [comment]
I want to thank you, @vilunov for all your effort. I stopped dedicating time to this project because there were no users for TensorFlow Haskell, or so I thought. I'm very happy to be wrong!

---

Oh boi. It's already been two years since I created this branch, so it took me quite some time to figure out what precisely I wanted it to do.

The whole problem with `Nat`s is that you cannot define dimensions without known sizes, which are very useful when you want to use the same NN with different batch sizes. These kind of sizeless dimensions are often signaled in Python with `None` (and `Nat` doesn't contain `None` :S). Thus, the goal of this branch was to try to add that same feature by extending `Nat`s.

My original idea was:

- Define `Dim` as `data Dim = D Nat | NoDim`
- Replace all `Nat` occurrences by `Dim` and extend the code to handle the case `NoDim` as if it was a dimension of size `1`.

Once that was done, we could write code like this:

~~~haskell
main11 :: IO (Vector 20 Float, Vector 120 Float)
main11 = runSession $ do
  (a :: Placeholder "a" '[ 'D 10, 'NoDim] Float) <- placeholder
  let cons = scalar 2.1
  op <- render $ a `add` cons
  let (input1 :: TensorData "a" [10,2] Float) = encodeTensorData . fromJust $ fromList [1..20]
      (input2 :: TensorData "a" [10,12] Float) = encodeTensorData . fromJust $ fromList [1..120]
  res1 <- runWithFeeds (feed a input1 :~~ NilFeedList) op
  res2 <- runWithFeeds (feed a input2 :~~ NilFeedList) op
  return (res1, res2)
~~~

But there are some weird cases where the code could typecheck even though it could fail at runtime:

~~~haskell
main12 :: IO (Vector 120 Float)
main12 = runSession $ do
  (a :: Placeholder "a" '[ 'D 10, 'D 2, D' 6] Float) <- placeholder
  (b :: Placeholder "b" '[ 'D 10, 'NoDim, D' 1] Float) <- placeholder
  op <- render $ a `add` cons  -- shape: [10, 2, 6], and NoDim should be forced to be 2
  let (input1 :: TensorData "a" [10,2,6] Float) = encodeTensorData . fromJust $ fromList [1..120]
      (input2 :: TensorData "b" [10,3,1] Float) = encodeTensorData . fromJust $ fromList [1..30]
  -- The compiler verifies whether the shape of `a` checks with the shape of `input2`, and
  -- whether the shape of `b` checks with `input2`, but that is not enough to ensure that all
  -- operations can be executed! THIS WILL FAIL AT RUNTIME!
  runWithFeeds (feed b input2 :~~ feed a input1 :~~ NilFeedList) op
~~~

To solve this I thought of doing something similar to what it had been done to placeholders. Namely, every `NoDim` carry a name and every `Tensor` carries a list with the value `NoDim sym`s should have. For this, `Dim` would be defined as:

~~~haskell
data Dim = D Nat | NoDim Symbol
~~~

A restriction on a dimension would be:

~~~haskell
data RestrictionDim = EqDim Symbol Symbol -- The dimensions `NoDim (Symbol 1)` and `NoDim (Symbol 2)` are the same
                    | SetDim Symbol Nat  -- The dimension `NoDim (Symbol)` has size `(Nat)`
~~~

And, `Tensor` would be:

~~~haskell
newtype Tensor (shape :: [Nat]) (placeholders :: [(Symbol, [Nat], Type)]) (restricts :: [RestrictionDim]) v a = Tensor (TF.Tensor v a)
~~~

With all of this in place, we could be able to write something like:

~~~haskell
main13 :: IO (Vector 120 Float)
main13 = runSession $ do
  (a :: Placeholder "a" '[ 'D 10, 'D 2, D' 6] Float) <- placeholder
  (b :: Placeholder "b" '[ 'D 10, 'NoDim "dim1", D' 1] Float) <- placeholder
  -- shape: [10, 2, 6], and NoDim "dim1" must be 2 (PS: `op` type is inferred and shouldn't be typed in)
  (op :: Tensor '[10,2,6] _ '[ 'SetDim "dim1" 2] Build Float) <- render $ a `add` cons
  let (input1 :: TensorData "a" [10,2,6] Float) = encodeTensorData . fromJust $ fromList [1..120]
      (input2 :: TensorData "b" [10,3,1] Float) = encodeTensorData . fromJust $ fromList [1..30]
  -- The compiler is able to check that `feed b input2` does not fulfill the
  -- requirement of `'SetDim "dim1" 2` from `op`, i.e. the code does not type check!
  runWithFeeds (feed b input2 :~~ feed a input1 :~~ NilFeedList) op
~~~

---

That is roughly what I thought it could be done, thus I created a branch to replace all `Nat` with `Dim` (and left it to gather dust for two years). But, after all that inner discussion, I arrived at a conundrum:

Should I try to implement all those changes for the sake of having varying batch sizes?

And what about the extra parameter `Tensor` now carries? Does the developer who works with tensors need to care about all those parameters `Tensor` has? Could `'[ 'D 10, 'D 7, 'NoDim "d"]` be written in a simpler way, something like `'[10, 7, 'NoDim' ]`?

So, that is it. That was the idea.

---

Sorry for the long and late reply.

Thanks for all.

Happy experimentation :)

**Comment by helq** [comment]
Btw, about a formatter, I used to use these two:

- https://github.com/jaspervdj/stylish-haskell
- https://github.com/chrisdone/hindent

But it's been a long time since I used them, so I'm not sure if there are more/better alternatives in the Haskell ecosystem.

**Pull request merged**
